### ISSUE TITLE
Download subs only

### ISSUE THREAD

**Issue by batestota** [DasKraken/CR-dl#1]
Hello
I love your work and how you updated very quick to support HTML5
I didn't know how to pull request so i post it here
can you please add a feature that only download the subtitle file without downloading the whole video file 

Thanks

**Comment by DasKraken** [comment]
Added.
In v2.3.0 you can now use ```--subsOnly``` to only download the subtitle files.

**Comment by batestota** [comment]
thaaaaaank you !!!!
you are the man
