### ISSUE TITLE
Cant download last episode

### ISSUE THREAD

**Issue by Wralui** [DasKraken/CR-dl#11]
All last episodes of series cannot be downloaded for some reason. 
It says :

> (HTML5 Player)
> Subtitles for  not available. Skipping...
> Error: Couldn't set enUS as default subtitle: subtitle not available.

But they are available in the web player.

**Comment by DasKraken** [comment]
Are you sure that you are logged in? ```cr-dl login <username> <password>``` 
The last episodes of airing series usually require a premium account.

**Comment by Wralui** [comment]
My bad, I recreated the cookies, cookies were 2ko long, usually 3ko, it's fine now, thanks for your help DasKraken !
