### ISSUE TITLE
Can't Select Multiple Seasons and Episodes

### ISSUE THREAD

**Issue by mtcdood** [DasKraken/CR-dl#12]
It's not possible to select `--seasons 1-3` and `--episodes 10-75` for RIN-NE to download the whole series starting with episode 10 for example. This would be a nice feature.

**Comment by wawa0078** [comment]
the feature already exist read usage option

Optional arguments:
Following optional arguments can be provided to 'download':

--season SEASON, --seasons SEASONS A season number or a comma-separated list (without spaces) of season numbers to download (eg. 1,2). Works only for series-links. Note: Season 1 is the bottom-most season on the website.

--episode EPISODE, --episodes EPISODES A comma-separated list of episode numbers to download. A - (minus) can be used to specify an area (eg. 01,03-05,SP2). Works only for series-links. If multiple seasons are available, you must specify one with --season.

**Comment by mtcdood** [comment]
You clearly didn't read the issue. Thanks for wasting everyone's time with your reply.
