### ISSUE TITLE
Correct subtitle styling

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#14]
Hello, 

I just discovered this amazing app,I love how flexible it is.

but I noticed something with subtitle files, they are all with the same styling.
Let me show you an example:
let's say I download this:
cr-dl download https://www.crunchyroll.com/ar/saki/episode-1-encounter-524846
it will create a temp folder and put subtitles within it
![image](https://user-images.githubusercontent.com/12091003/56938492-fa9dc780-6b0a-11e9-8530-94134d14e87b.png)
it should download 6 subtitle files:
![image](https://user-images.githubusercontent.com/12091003/56938516-25881b80-6b0b-11e9-9970-05ccf610f528.png)

if you open them all, you will notice each one of them have their own styling.
![image](https://user-images.githubusercontent.com/12091003/56938538-43558080-6b0b-11e9-8536-8a56f4692ec4.png)

As you can see the font here is ``Trebuchet MS``

Currently I am using https://github.com/Xonshiz/anime-dl tool to download, but the developer sopped patching it for a while now, and it cannot handle some of animes currently, but it download subtitles with current styling:
![image](https://user-images.githubusercontent.com/12091003/56938844-1e620d00-6b0d-11e9-8373-1e27a3478ee5.png)

As you can see the font name here is Adobe Arabic

I actually don't know what the real cause of this, but I noticed something, in CR-dl subtitle file there are these lines:
```
PlayResX: 848
PlayResY: 480
```

I know that Crunchyroll offer different subtitle file for video quality 480 and below, and another subtitle file for 720 and above.

I think anime-dl can download different subtitle for each quality, could you please check it.

because ``Trebuchet MS`` is not supporting Arabic, so I wish this app can download the correct subtitle file for the selected resolution with correct styling.

**Comment by Abu3safeer** [comment]
If it is not possible to get that, will there by any styling method? so at least I can set the font in CLI command?

**Comment by DasKraken** [comment]
Hello,

cr-dl takes the .ass files directly from crunchyroll without any modification so it's indeed weird that they use a font that doesn't support the language:
![cr-trebuchet](https://user-images.githubusercontent.com/42367146/56982361-7175a780-6b81-11e9-8814-2a3f95fcbc66.png)

I quickly looked into https://github.com/Xonshiz/anime-dl .  They use the old method for getting subtitles which was used for the flash player, so maybe there is maybe a difference in the subs.

 >  I know that Crunchyroll offer different subtitle file for video quality 480 and below, and another subtitle file for 720 and above.

I actually don't know anything about this. I checked again and I can only find one subtitle file for each language. Maybe there used to be different subtitles for different resolutions for the flash player but thats not the case anymore.

Currently CR-dl has no method to change the font. Best you can do is getting subtitles and video separatly (`--subsOnly` and `--subLangs none`). Changing the font manually and mux them with ffmpeg, mkvmerge, Handbrake or whatever.

You are right that Trebuchet MS is not supporting arabic, but it seems to be readable just fine on video players anyway or is it unreadable for you?

**Comment by Abu3safeer** [comment]
It is readable because The system uses the fallback font, so what you see is not Trebuchet MS.
but the issue really is not the font itself, it is just that using Trebuchet MS has no effect, and I want to get the best of it.

so now: 
1 - I need to try to get the flash player subtitle and check the font by myself, it might be better than HTML5 player.
2 - Is there anyway to mux font automatically? like creating a folder and name it "Fonts" so CR-dl will mux all fonts inside it automatically.
3 - I will check flash player then I will see what I can suggest.

**Comment by DasKraken** [comment]
I checked the flash player subs and they indeed used different fonts, but I also checked some other videos and there were the same fonts for both.

CR-dl has still some legacy code left for the flash player subs https://github.com/DasKraken/CR-dl/blob/40f3017be2013952bf7f7f4c91462a6514afb77e/src/CrDl.js#L469-L477
But I was planning on completly removing it.

It may be not pretty but sorry this hasn't a high priority for me.

**Comment by Abu3safeer** [comment]
Actually I wonder why they use different font for HTML5 player, I mean Crunchyroll official font for Arabic is "Adobe Arabic" it is been used for years, but since they used HTML5 player all "Adobe Arabic" font has become Trebuchet MS, but when I run the same video with Flash player it returns to "Adobe Arabic"

keep in mind that this only happens with animes translated before HTML5 player support, once they support HTML5 player all fonts become "Adobe Arabic" in both HTML5 player and flash player.

so using CR-dl with new animes would be amazing.

> But I was planning on completly removing it.
You could add --lagesyplayer so this app use the legacy one, that would solve the issue completely, and wont effect any current user.

**Comment by DasKraken** [comment]
I've added the option `--legacyPlayer` in v3.2.0 now. This will only download the subtitles using the old method. Everything else still uses the html5 player method as CR seems to have made some changes and the code doesn't work correctly anymore.

**Comment by Abu3safeer** [comment]
I tried to contact them, they say that Flash Player has the correct fonts, and they are migrating them to HTML5, but that would take time, they didn't say how much time exactly. 

so I will keep on using the old flash player until this fix them.
