### ISSUE TITLE
Can you auto mux fonts with the mkv? 

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#15]
Hello.

I like this app, it has many features that would make me select it over others, but could you add muxing fonts with the mkv? 

You could use --fonts DIROCTORY/TO/FONTS or set it to Fonts by default, so if the app find folder called fonts, it should mux this with the video.

I have mentions on #14 that anime-dl has this feature, and to be honest, it is an amazing feature.

I know that I am new to this project, I just knew about it yesterday, but I can see how beautiful is this app, it is really promising, especially the windows binary is extremely easy to use, all other apps requires at least installing one or more components in order to work properly.

**Comment by DasKraken** [comment]
Actually this is a feature i'd like to see myself.

Well, attaching fonts is not difficult to implement, just something like:
```ffmpeg -i INPUT -attach FONT.ttf -metadata:s:t:0 mimetype=application/x-truetype-font out.mkv```

But instead of attaching all fonts specified by user I could also make it automatically select and download the ones that are needed by the subtitles (They are provided by Crunchyroll e.g. https://static.crunchyroll.com/vilos/assets/fonts/AdobeArabic-Bold.otf)
Would this be maybe better?

**Comment by Abu3safeer** [comment]
> Actually this is a feature i'd like to see myself.
> 
> Well, attaching fonts is not difficult to implement, just something like:
> `ffmpeg -i INPUT -attach FONT.ttf -metadata:s:t:0 mimetype=application/x-truetype-font out.mkv`
> 
> But instead of attaching all fonts specified by user I could also make it automatically select and download the ones that are needed by the subtitles (They are provided by Crunchyroll e.g. https://static.crunchyroll.com/vilos/assets/fonts/AdobeArabic-Bold.otf)
> Would this be maybe better?

WOW, I never now that Crunchyroll provide the subtitle from their CDN, of course this would be FANTASTIC!! 
Just go ahead, you have plenty of amazing ideas that would make this app way step ahead any other tool!

**Comment by Abu3safeer** [comment]
You did great job, testing time 😁
