### ISSUE TITLE
Conflict between downloading to files in the same directory. 

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#18]
Hello everyone,

I wanted to download both softsub and hardsub versions, so I created two .bat files that will download each of them.

But I have noticed that they both use the same temp directory, so they conflict with each other. 
so can you please make them use some unique id in the temp directory like "temp-rp8mucdwrag3"

You might say "can't you just created separate directories for each .bat file of them?"
Actually yes, that what I am doing right now, but in this way i would need to make a new directory for each download, or even worse, if I make a gui the execute commands, it would execute every command in the same directory so they certainly will conflict. 

Or do you have better idea than this?

**Comment by DasKraken** [comment]
I think thats a good idea. I'll propably make it that way sometime soon.

**Comment by Abu3safeer** [comment]
Hello @DasKraken , any updates?

**Comment by DasKraken** [comment]
Sorry that it took so long, the last few weeks were very busy for me IRL.

**Comment by Abu3safeer** [comment]
No problems at all @DasKraken , I just wanted to remind you if you forgot, you know how life makes you forget sometimes.
