### ISSUE TITLE
Unsupported url

### ISSUE THREAD

**Issue by Barbait** [DasKraken/CR-dl#19]
Hello i'm trying to download an anime series but it gives me simply an "Unsupported url" error.

I'm using the x64 windows package downloaded from the last release.

this is the command i input in the windows terminal:
```
cr-dl.exe download -c 10 --listSubs itIT,esES,frFR,enGB  https://www.crunchyroll.com/the-ancient-magus-bride
```
i've tried various ulrs, also with the variation from this:
```
https://www.crunchyroll.com/the-ancient-magus-bride
```
to this:
```
https://www.crunchyroll.com/it/the-ancient-magus-bride
```

**Comment by DasKraken** [comment]
You propably want `--subLangs` instead of `--listSubs`. `listSubs` doesn't take any parameters and therefore in your example `itIT,esES,frFR,enGB` is interpreted as beeing an URL.

This following command is working fine:
```
cr-dl.exe download -c 10 --subLangs itIT,esES,frFR,enGB --season 9 https://www.crunchyroll.com/the-ancient-magus-bride
```
