### ISSUE TITLE
How to download when there are no subtitles available?

### ISSUE THREAD

**Issue by CloseAsDeath** [DasKraken/CR-dl#2]
I tried to download this chapter http://www.crunchyroll.com/miss-kobayashis-dragon-maid/episode-3-start-of-a-new-life-that-doesnt-go-well-of-course-776554 but failed everytime, it says "subtitles for [any] not available, couldn't set [any] language as default, subtitle not available" (tried with all possible languages)

I execute --listSubs and 0 subs are available

I only want the chapter with spanish dub, subs isn't necessary in this case. is there a way to download the video+audio without subs?

**Comment by DasKraken** [comment]
Fixed.
In v2.3.0 videos without subtitles work now. And you can use ```--subLangs none``` to download without subs.
