### ISSUE TITLE
RuntimeException ffmpeg

### ISSUE THREAD

**Issue by diasDominik** [DasKraken/CR-dl#20]
im downloading Naruto Shippuden so far no problem but now i have an RntimeExpetion on the 14th Season Episode 297-...
I tried Episode 298 same Problem.
I use Windows 10.
Episode 296 have no Problems.
`RuntimeException: ffmpeg process exited with code 1
    at ChildProcess.module.exports.proc.on (J:\snapshot\CR-dl\src\processVideo.js:0:0)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)`
![Unbenannt](https://user-images.githubusercontent.com/15254968/58259587-23fdec00-7d75-11e9-92d8-3a9cfaa2138d.PNG)

**Comment by DasKraken** [comment]
So, the reason for this is that Windows has a path length limit of 260 characters and the filepath exceeds that limit:
```
/Naruto Shippuden - Staffel 14_ Der vierte große Shinobi-Weltkrieg - Angreifer aus dem Jenseits [1080p]/Naruto Shippuden - Staffel 14_ Der vierte große Shinobi-Weltkrieg - Angreifer aus dem Jenseits - 297 - Wünsche des Vaters und Liebe der Mutter [1080p].mkv
```

A workaround is to use an output template like  `-o "Naruto Shippuden - {episodeNumber} [{resolution}].mkv"`

**Comment by diasDominik** [comment]
thanks
