### ISSUE TITLE
What is the syntax of http proxy? and does it support user login?

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#21]
Hello, 
I wonder what is the syntax, is it "host:port"? if that is correct then where to enter user details? 

I am using NordVPN, and it requires to enter user details to login.

**Comment by DasKraken** [comment]
The syntax is just the URI syntax: `http://username:password@host:port`.
But make sure to [percent-encode](https://en.wikipedia.org/wiki/Percent-encoding) reserved characters in username and password. Especially when using an email adress `@` needs to be encoded to `%40`.
For NordVPN this should look like:
```
 --httpProxy "http://something%40gmail.com:Pass123@us3837.nordvpn.com:80" 
```

**Comment by Abu3safeer** [comment]
Thank you..

Cloud you write this into the readme?

**Comment by Abu3safeer** [comment]
Looks like using %40 instead of @ will result:
```
status: 407,
  statusText: 'Proxy Authentication Required',
  url: 'http://www.crunchyroll.com/videos/anime' }
```

but it works with @, so looks like this app takes care of encoding the url.
