### ISSUE TITLE
This episode is not downloading (others work)

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#22]
Hello,

This episode does not work, I don't know why:
https://www.crunchyroll.com/ar/one-punch-man/episode-9-the-ultimate-dilemma-783088

![image](https://user-images.githubusercontent.com/12091003/59298556-7440dd80-8c93-11e9-98b8-2d570499a1d3.png)

The command is:
```
SET URL="https://www.crunchyroll.com/ar/one-punch-man/episode-9-the-ultimate-dilemma-783088"
cr-dl download -l arME --attachFonts -c 32 -o "crunchyroll softsub/{seasonTitle} - {episodeNumber} [{resolution}].mkv" --httpProxy "****@de562.nordvpn.com:80" %URL%
pause
```

**Comment by DasKraken** [comment]
You seem to be using a german proxy although this series isn't available in that country. You could try to do it without proxy (and delete cookies.data) if you live in a country where its available. 
Unfortunately crunchyroll even seems to detect all NordVPN servers as being in US and this series isn't available there so it propably wouldn't work just switching servers.

**Comment by Abu3safeer** [comment]
Oh no, I forgot that completely, I use a server but it is blocked from crunchyroll, so I have to use a proxy for that, looks like I will try different countries until I find a good one.

Thank you very much.
