### ISSUE TITLE
Cant download dub

### ISSUE THREAD

**Issue by Wralui** [DasKraken/CR-dl#25]
Hi, I cant download simple video without sub, is just me or ?

**Comment by DasKraken** [comment]
Videos without subs should just work and you can specify `--subLangs none` to make sure that no subtitles are included. 
If you have a link or command where it doesn't work as supposed, please post it here.

**Comment by Wralui** [comment]
My bad, I forgot to put subtitle to none for dubs ! Thanks for your help.
