### ISSUE TITLE
Problem with the last version

### ISSUE THREAD

**Issue by darkairo** [DasKraken/CR-dl#26]
Hello Master! I have the following problem : 

[]
RuntimeException: No resolutions found.
    at getMaxWantedResolution (J:\snapshot\CR-dl\src\CrDl.js:0:0)
    at Object.downloadVideoUrl (J:\snapshot\CR-dl\src\CrDl.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I hope you can make some fix.

Greetings!

**Comment by Abu3safeer** [comment]
The same here:
RuntimeException: No resolutions found.
    at getMaxWantedResolution (J:\snapshot\CR-dl\src\CrDl.js:0:0)
    at Object.downloadVideoUrl (J:\snapshot\CR-dl\src\CrDl.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by lonewolf8209** [comment]
> RuntimeException: No resolutions found.
>     at getMaxWantedResolution (/usr/lib/node_modules/cr-dl/src/CrDl.js:200:11)
>     at downloadVideoUrl (/usr/lib/node_modules/cr-dl/src/CrDl.js:545:32)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:189:7)

thank god, i thought i was the only one after the latest update

**Comment by Abu3safeer** [comment]
@lonewolf8209  it happens of both batch and single download for me.

**Comment by lonewolf8209** [comment]
> @lonewolf8209 it happens of both batch and single download for me.

i said i was using a different program to download them 1 by 1

**Comment by Wralui** [comment]
Is this related to the new widevine security ?

**Comment by Abu3safeer** [comment]
I don't think that, this app still can get the subtitle and fonts, the only issue is with the resolution, so it might be because of changing the source of qualities.

lets wait for @DasKraken .

Unfortunately I am not expert in node so I didn't manage to analyse the script, plus there is no verbose option so we can see where it stops working.

**Comment by Wralui** [comment]
Crunchyroll will change their security soon to full widevine (which is painfull to bypass without good knowledge in security...) For now, they still have HLS(m3u) decrypted, that you can still pick in source code of the page, but a matter of time they will remove it for widevine protection...
I see that they have put "Adaptive" for resolution, maybe the problem to catch the resolution is there, who knows...

**Comment by Abu3safeer** [comment]
@Wralui You might be correct, I could not find the m3u8 url, so looks like they have change the encryption.

**Comment by lonewolf8209** [comment]
that's going to suck, hopefully these tools don't go private like the amzn downloaders

**Comment by darkairo** [comment]
That's not right guys, using the Firefox extension called "HLS Stream detector", I can keep capturing the streamings and I can dump them in RAW with VLC, obviously it's not the most comfortable way but I don't think they changed anything important but, I think not even the plugin would work, regards!

**Comment by Wralui** [comment]
@darkairo this is what im saying... HLS is still up, but who knows for how long

**Comment by darkairo** [comment]
I have used another GUI that at the moment does not give me problems, (Obviously while this is being fixed), and I have not had any type of problems, it is not a new GUI so I think it can be just some error with the instructions to ffmpeg

**Comment by Abu3safeer** [comment]
Any update?

**Comment by Abu3safeer** [comment]
looks like they have switched from m3u8 to mpd for softsub, I am only able to find the hardsub stream links.

but on the other hand the subtitle is now not encrypted, it is just plain ass file.

**Comment by Wralui** [comment]
No, you are just not picking the right thing, 
> "hardsub_lang": null,

Is the right one.

I found a script that still works for the moment https://github.com/seiya-dev/crunchyroll-downloader-nx
I hope this last for a long time...

**Comment by Abu3safeer** [comment]
@Wralui is you notice it is "harsub_lang" not softsub.

**Comment by tnovais** [comment]
Any predictions to correct?

**Comment by Abu3safeer** [comment]
I tried to mess with the application, but no luck, I am not experienced with node applications.

**Comment by Wralui** [comment]
> 
> 
> @Wralui you should notice it is "harsub_lang" not softsub.

its written hardsub, but with "null" value it is not, you should check again...

**Comment by Abu3safeer** [comment]
@Wralui  You are right, it was in front of me all time, I was looking in the wrong code.
Thank you very much.

**Comment by Abu3safeer** [comment]
Any updates @DasKraken ?

**Comment by DasKraken** [comment]
Sorry for the late answer. So the issue was here just that CR-dl currently can only handle HLS Streams but CR recently added DASH Streams and put them on top of the list. 
The fix is easy for now and should work again as of 6bccd422958b9f8c3e191c136fb08fc9d8db0fc4 but like @Wralui said, they seem to be changing to Widevine DRM and when they disable the unprotected Streams, downloading won't be easily possible anymore.

**Comment by Abu3safeer** [comment]
Hello @DasKraken , Actually I have managed to download the DASH stream using youtube-dl, so if they replaced HLS with DASH completely, there might be a way to download the stream.

I suggest you to try youtube-dl for now to be prepared for what is coming.

This is the youtube-dl command I use:
```
youtube-dl -f bestvideo+bestaudio "DASH STREAM LINK GOES HERE"
```

To be honest while CR-dl was not working, I felt empty, there is no tool that offer the compatibility and simplicity as your app.

You are really doing GREAT JOB.

**Comment by DasKraken** [comment]
Hi @Abu3safeer ,
if they replaced HLS with DASH it would be a bit of work but possible to make it work. The issue is that they currently have 3 types of streams: `DASH`, `HLS` and `DASH with DRM` and I assume that they will leave `DASH with DRM` as the only option in the future to prevent people from downloading. Although some people are able to decrypt DRM streams it definitely won't be publicly available, so CR-dl and youtube-dl will stop working.

**Comment by Abu3safeer** [comment]
Oh, I see, looks like I tried DASH only, not the one with the DRM.
