### ISSUE TITLE
Proxy Not Working

### ISSUE THREAD

**Issue by ghost** [DasKraken/CR-dl#28]
Hi! I tried to download My Hero Academia with proxy but not working. I got every time this message https://imgur.com/93TvoZM

**Comment by DasKraken** [comment]
Hi, 
try deleting the file "cookies.data" and try again.

If this doesn't work, maybe the series isn't available the country of your proxy or it is possible that your proxy is completely blocked by crunchyroll.

**Comment by bendeguzbagi** [comment]
I made that proxy with google cloud vps and setted the location in us. What else i can do?

**Comment by bendeguzbagi** [comment]
Can you help me out with a proxy? :D i only need this one anime from there ><
