### ISSUE TITLE
Episodes not found

### ISSUE THREAD

**Issue by darkairo** [DasKraken/CR-dl#3]
**Hello, I hope you're ok !, since 3 days ago that the normal use of cr-dl is not working, maybe some change on the Crunchyroll site, any link per episode seems not to be understood by the commands, saying that the episode can not find, but if we take the url of the complete series, download all episodes without problems, the problem is when there is no space and you would have to download all the episodes every week, I will inform you in case nobody else had done it, Greetings and I hope you can give me news.
**

**Comment by Joemag** [comment]
Thanks for report. I looked into it, and it's because CR changed their episode URLs to include the language: from "crunchyroll.com/<SERIES>/<EPISODE>-<ID>" to "crunchyroll.com/<LANGUAGE>/<SERIES>/<EPISODE>-<ID>". So cr-dl wrongly classified it as a series URL.
Update is on the way.
