### ISSUE TITLE
Cannot detect Arabic subtitle where it is available

### ISSUE THREAD

**Issue by Abu3safeer** [DasKraken/CR-dl#30]
Hello everyone.

https://www.crunchyroll.com/ar/is-it-wrong-to-try-to-pick-up-girls-in-a-dungeon/episode-1-bell-cranel-adventurer-678135

It says no arME subtitle though there is subtitle

![image](https://user-images.githubusercontent.com/12091003/68151445-c9d39a80-ff52-11e9-8843-409e9da72d35.png)
![image](https://user-images.githubusercontent.com/12091003/68151576-03a4a100-ff53-11e9-8fb0-06ab70fb9361.png)

**Comment by DasKraken** [comment]
Works for me. 
![grafik](https://user-images.githubusercontent.com/42367146/68550503-92a63300-0403-11ea-84d7-9b1120d06505.png)
Try deleting cookies if you changed VPN/Proxy location.

**Comment by Abu3safeer** [comment]
Thank you @DasKraken , never thought of this, After deleting cookies it just worked.
