### ISSUE TITLE
Can't download anime without subtitles

### ISSUE THREAD

**Issue by Vinschers** [DasKraken/CR-dl#36]
Hello,

I'm trying to download this episode https://www.crunchyroll.com/pt-br/konosuba-gods-blessing-on-this-wonderful-world/episode-2-an-explosion-for-this-chunibyo-781770 with the command
`cr-dl download --subLangs none https://www.crunchyroll.com/pt-br/konosuba-gods-blessing-on-this-wonderful-world/episode-2-an-explosion-for-this-chunibyo-781770 `
But this error shows
`(HTML5 Player)
No subtitles will be included.
Error: No stream found for hardsub language: null`

I just want to download without this dubbed version without subtitles. I don't know why, but the first episode (https://www.crunchyroll.com/pt-br/konosuba-gods-blessing-on-this-wonderful-world/episode-1-this-self-proclaimed-goddess-and-reincarnation-in-another-world-781769) works fine with the same command.

**Comment by whoamikyo** [comment]
try remove --subLangs none

**Comment by whoamikyo** [comment]
btw, try use cr-dl download --subLangs none https://www.crunchyroll.com/pt-br/konosuba-gods-blessing-on-this-wonderful-world/episode-2-an-explosion-for-this-chunibyo-781770 --subLangs ptBR --hardsub

works for me.

**Comment by DasKraken** [comment]
Hi,
so, the episodes 2 and later require premium access. Use `cr-dl login <username> <password>` to download using a premuim account.
