### ISSUE TITLE
Having issues setting subtitle language to enUS (Subtitle not available)

### ISSUE THREAD

**Issue by elnathanau1** [DasKraken/CR-dl#37]
I was trying to download Love is War Ep 1 with 
```
cr-dl download --subLangs enUS -o "Love_is_War_S1E{episodeNumber}.mkv" https://www.crunchyroll.com/kaguya-sama-love-is-war/episode-1-i-will-make-you-invite-me-to-a-movie-kaguya-wants-to-be-stopped-kaguya-wants-it-781498 720p
```
but I am getting 
```
Subtitles for enUS not available. Skipping...
Error: Couldn't set enUS as default subtitle: subtitle not available.
```
This was also occurring when I tried to download Shokugeki no Soma. I checked online and English(US) is listed as subtitle options.

**Comment by testtim2** [comment]
Same !

**Comment by DasKraken** [comment]
I can't reproduce. 
Is it possible that you are in a country that has no access to this series? If you're using a VPN try deleting cookies.data

**Comment by GabenRulez** [comment]
I have the same problem. Deleting cookies.data seems to work (if I use --listSubs), but when I change that to --seasons 1-2 it cames back, and deleting it doesn't make a difference.

**Comment by GabenRulez** [comment]
I'm back after some testing. 
My problem was that the series had this little "trailer", that didn't have any subtitles and downloading whole series "at once" was interrupted.
The VPN problem with "subtitles not available" that I had while trying to download single episode was not a case after deleting cookies.data

**Comment by DasKraken** [comment]
Should have better error description in 4.0.0 now
