### ISSUE TITLE
Can't login when capture is needed

### ISSUE THREAD

**Issue by ark626** [DasKraken/CR-dl#38]
For users of a VPN there seem to be no possibility to login when CR requests a captcha on login.

![grafik](https://user-images.githubusercontent.com/10487166/75404581-41b33f80-590b-11ea-9ed7-255a1ab997c6.png)

Since i couldnt figure out a solution i opened an issue.
A solution would be to include a import cookie option, where a raw text cookie could be used.

**Comment by Abu3safeer** [comment]
Even without a VPN this still happen, today I cannot login at all.

**Comment by GabenRulez** [comment]
Try deleting cookies.data that sits inside your CR-dl folder (where your .exe sits).
Works for me.

**Comment by DasKraken** [comment]
Importing cookies now possible: [Alternative login methods to CR-dl](https://github.com/DasKraken/CR-dl#alternative-login-methods-to-cr-dl)
