### ISSUE TITLE
Problem with season and episodes

### ISSUE THREAD

**Issue by valascus** [DasKraken/CR-dl#4]
Hey!
First, i want to appreciate your work, as it's, by far, the best simple crunchyroll downloader. With this in mind, I'm having a issue right now.

So, I'm downloading One Piece. One Piece has a Special HD version for the older chapters, and I'm downloading them (season 1 means season 2, season 2 means season 4, etc.) but... last time i let the computer downloading but it didn't finish. 

I'm trying to run: 

`cr-dl download --subLangs ptBR https://www.crunchyroll.com/one-piece 1080p --season 4 --episodes 1` (should mean episode 136, the first of the season)

and even

`cr-dl download --subLangs ptBR https://www.crunchyroll.com/one-piece 1080p --season 4 --episodes 136`  (the actual episode number. can't run only --episodes because i want the season 4 (hd special) edition).
How could I do this? If not. Could you, in a near future add this feature?

And also, to be perfect, and if you have some time, I noticed that he doesn't check for already downloaded episodes. It downloads and overwrites the already downloaded file. That would be great. Once again, thank you for making THE BEST (and i'm serious) CR downloader.

Oh, and proxies for login would be great :p

**Comment by DasKraken** [comment]
Hi,
I looked into this, but for me "Episode 136 Special HD" is in season 6 (sixth Panel from below), so ```--season 6 --episodes 136``` works for me, or am I missing something?

Checking for already downloaded files and proxies should actually be easy to implement, so it's pretty likely that I'll add them during the next few days :)

**Comment by valascus** [comment]
Oh shittt xD
My bad... I'm sorry. That probably works. Not home right now, but I believe it works. 
Thank you for checking that and hope to see news soon :D
