### ISSUE TITLE
It stopped working

### ISSUE THREAD

**Issue by Varo412** [DasKraken/CR-dl#41]
![imagen](https://user-images.githubusercontent.com/48073509/76703693-98729480-66d3-11ea-8a46-f52e78dd2511.png)

**Comment by GabenRulez** [comment]
"Connection timed out" - it took to long to get response from the server.
It was either your internet problem, or Crunchyroll servers problem.

Your best bet is to try again, and if it doesn't work - check all of your internet peripherals.

**Comment by DasKraken** [comment]
I guess it was a temporary server promlem. closing
