### ISSUE TITLE
Cloudflare (?) shenanigans

### ISSUE THREAD

**Issue by adracamas** [DasKraken/CR-dl#48]
Not sure what exactly you are using to program this.. is it Python? If so maybe this will help ( I don't know enough about any of this to be of any help)
https://stackoverflow.com/questions/36948573/download-files-from-website-with-cloudflare-using-python

Not including the massive { } I got in the command line.. but at the end it gave 
`  status: 503,
  statusText: 'Service Temporarily Unavailable',
  url: 'http://www.crunchyroll.com/videos/anime' }`
Parts of the inline included mention of cloudflare ddos protection etc. Sorry if this isn't of much help or informative but thought I'd bring it up ( it WAS working last night though)

**Comment by DasKraken** [comment]
too little details
