### ISSUE TITLE
Instalation Problem

### ISSUE THREAD

**Issue by theruleof4** [DasKraken/CR-dl#50]
When I try to install by the command, show me this message:

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/DasKraken/CR-dl.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

Someone knows whats going on?

**Comment by DasKraken** [comment]
you need to install [git](https://git-scm.com/)
