### ISSUE TITLE
No episodes found

### ISSUE THREAD

**Issue by theruleof4** [DasKraken/CR-dl#52]
For some reason, some links are showing the message "no episodes found" even though they exist, and don't start to download it

This link for example, on the page, has the episodes list, but the program does not detect https://www.crunchyroll.com/digimon-adventure-tri

**Comment by DasKraken** [comment]
It's possible that they aren't showing because of your selected language. Try ```cr-dl language enUS```. And if you're using proxy or vpn try deleting cookies.data and try again.
