### ISSUE TITLE
Can't login in Version 4.0.0

### ISSUE THREAD

**Issue by chichid95** [DasKraken/CR-dl#55]
Hello,
I just upgraded to version 4.0 but unable to login

> root@BK-201-PC-FIXE:/mnt/e/DL-RIP/CR-DL# cr-dl login "[username] [password]"
> /usr/local/lib/node_modules/@derkraken/cr-dl/node_modules/got/dist/source/create.js:101
>     got.paginate = async function* (url, options) {
>                                  ^
> 
> SyntaxError: Unexpected token *
>     at createScript (vm.js:80:10)
>     at Object.runInThisContext (vm.js:139:10)
>     at Module._compile (module.js:616:28)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/@derkraken/cr-dl/node_modules/got/dist/source/index.js:7:18)

[https://discordjs.moe/b-_77lrH738.png](url)

**Comment by DasKraken** [comment]
Which node version are you using? `node -v`

**Comment by chichid95** [comment]
Hello, I have version v8.10.0

**Comment by chichid95** [comment]
Ok i upgrade to version 13. Thank you
