### ISSUE TITLE
Does it works in production environment like Heroku ?

### ISSUE THREAD

**Issue by Gregory280** [DasKraken/CR-dl#56]
I made a simple app with ruby on rails which consist in just a form page in which capture the login and crunchyroll url. Behind de scenes my controller run the shell command to login and download. On my local machine it works fine. I tried to deploy on heroku but whenever I run npm install to install the dependencies my app crashes. I'm really an amateur, maybe I'm trying to doing something that actually does not work the way I think it is.

**Comment by DasKraken** [comment]
Does the log give any output what might have gone wrong? `heroku logs --tail`. I'm not experienced with heroku, but basically you need to install node and ffmpeg i guess like
```bash
heroku buildpacks:add https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
heroku buildpacks:add heroku/nodejs
```
And on the server running `npm install -g @derkraken/cr-dl@4.0.0` should work or alternatively
```bash
git clone https://github.com/DasKraken/CR-dl.git
cd CR-dl
git checkout v4.0.0
npm install
npm run build
npm install -g .
```

**Comment by Gregory280** [comment]
Wow, I actually finally could run the CLI-tool on heroku bash. It worked ! My application still does not install the dependencies I'm trying to figure it out now. Its like heroku does not installing the dependencies when deploying. Everytime that I need to open the bash I need to run npm install and npm fund to get the CLI-tool working. Now I'm looking how get things working when pushing to heroku master. 
I'm trying things right now. What I did now was to add in my package.json this code:

        "scripts": { "postinstall": "npm install && npm fund" }

I don't know if this will work since is taking a while to end the pushing...but I do think I'm missing something more important about my app. It wont download through the browser as I was imagining right ? I mean, in the back-end I basically have this 3 lines of code

        system "cr-dl login #{@download.username} #{@download.password}"
        system "cr-dl download #{@download.url}"
        system "cr-dl logout"

This won't pop up a download window to the user save in their machine, right ? Maybe the video will be stored into public folder or even creating a new folder with the anime name as it happens runnig the cli-tool on local machine. 

Could you give me some guidance on what should I be looking up to be able to do that.

**Comment by Gregory280** [comment]
Yeah..I didn't work.
