### ISSUE TITLE
Hi please

### ISSUE THREAD

**Issue by Yogioh969** [DasKraken/CR-dl#60]
I am a member of a site https://shahid.mbc.net/

It is a website similar to netflix but for arabic content

Previously, I could download from the website by taking the link for the video by internet download manager as m3u8 format ,, like this line

https://cdxmd05-ak.akamaized.net/43879ec8-c913-464e-9a2a-6938714b685f/3000060014_TXMHD...ilter=144_1080)

and download it

but now the site bring new Encrypt like netflix use (DRM) ,, and when I use internet download manager to get video download line it give me alot of line Not downloadable ,, like this one

https://cdxmd05-ak.akamaized.net/018a3bc5-5903-42b6-ae96-cdf9f8847946/3000061337_STXOP...t=mpd-time-csf)

can any one help me with script like CR-dl  to download  from this site ??

i will pay for you i also need to contact you but i don't know how to get your email

**Comment by DasKraken** [comment]
Thats right. By default crunchyroll now uses DRM encrypted streams, but they still provide unencrypted ones.
If you disable DRM playback in your browser settings, it'll fall back to unencrypted stream.

How to use CR-dl is described in [README.md](https://github.com/DasKraken/CR-dl/blob/master/README.md). If you have trouble using command line, you can find instructions online. e.g. [heres one for youtube-dl, which works similar to CR-dl](https://www.youtube.com/watch?v=7wfUUZvybPY).

If you need to contact me privately, you can send an email to sparklingCookie@mail.com

**Comment by Yogioh969** [comment]
Thank You So Much
