### ISSUE TITLE
Cannot read property 'mkdir' of undefined

### ISSUE THREAD

**Issue by DJSorad** [DasKraken/CR-dl#62]
Tried to update to the latest release since I was also receiving the captcha lockout and now I am receiving this error. Any help is appreciated.
![cr-dl error](https://user-images.githubusercontent.com/66727184/84258252-39f36180-aadc-11ea-8cac-516ef294dee9.JPG)

**Comment by DasKraken** [comment]
Looks like your version of Node.js is outdated

**Comment by DJSorad** [comment]
Yup, was just about to close this as you replied. Thanks for the quick reply.
