### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by RoyRiv3r** [DasKraken/CR-dl#73]
Is this project dead ? 
I cant download anymore, captcha problem
any news ? 

Thanks.

**Comment by n0x073** [comment]
Crunchyroll changed some part on their sites.
Dont know if the maintainer still active but here is the pull request for fixing this issue: #75

**Comment by Tizioincognit0** [comment]
Try this fork: https://github.com/n0x073/CR-dl.

**Comment by RoyRiv3r** [comment]
Alright ! Thanks i'll try it out
