### ISSUE TITLE
New error 503

### ISSUE THREAD

**Issue by Smallkan** [DasKraken/CR-dl#8]
Fetching series:

![image](https://user-images.githubusercontent.com/9128062/53511235-b35d7100-3a9e-11e9-929e-1a0f0d4e0159.png)

**Comment by darkairo** [comment]
status: 503,
statusText: 'Service Unavailable',
url: 'http://www.crunchyroll.com/videos/anime' }

Same here, greetings!

**Comment by DasKraken** [comment]
Looks like Crunchyroll now requires the cloudflare browser check for every page and not only how it used to be on home and login page.
Fortunately I already have the code for solving it.

**Comment by DasKraken** [comment]
Should be fixed now by 367280819fec137d29cbfae08d9a7606da3df8b4

**Comment by darkairo** [comment]
You are the master DasKraken!! Thanks for everything!
