### ISSUE TITLE
I can´t mux in the new version

### ISSUE THREAD

**Issue by darkairo** [DasKraken/CR-dl#9]
I was able to log in without problems, I hit a link and was actually downloading the episode, the problem arrives at the moment of the muxing, the following error appears:

```
RuntimeException: ffmpeg process exited with code 1
    at ChildProcess.module.exports.proc.on (C:\snapshot\CR-dl\src\processVideo.js:0:0)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

I was able to get the subtitles I needed from the tmp folder before the error occurred and I was able to download the episode without subtitles, later with MKVtoolnix I was able to join them so the new version was very helpful, I informed you about this if you can detect the error, greetings!

**Comment by Wralui** [comment]
Hello, same here, in the exe version. 
Maybe path problem or ffmpeg, who knows...

**Comment by DasKraken** [comment]
Really weird error. While on linux ffmpeg searches for the video files relatively to the m3u8 file, on windows it looks relatively to the working directory. 
Btw. with ```--hideProgressBar``` you can see the output log of ffmpeg.
